import type { Metadata } from "next";
import Link from "next/link";
import { DEAL_TYPE_EN, EN_SITE_URL, SITE_NAME_EN } from "@/lib/en";
import { SITE_URL, X_PROFILE_URL } from "@/lib/site";
import { DEAL_TYPES } from "@/types/article";

const title = "About & Disclaimer";
const description = "About this site's operating policy, data sources, and disclaimer.";

export const metadata: Metadata = {
  title,
  description,
  alternates: {
    canonical: `${EN_SITE_URL}/about`,
    languages: { ja: `${SITE_URL}/about`, en: `${EN_SITE_URL}/about` },
  },
};

const WHO_ITEMS = [
  { term: "Institutional investors (domestic & foreign)", body: "Pension funds (e.g. GPIF), mutual funds, life insurers, sovereign wealth funds" },
  { term: "Hedge funds", body: "Funds pursuing absolute returns over short-to-medium terms (heavy use of short-selling and derivatives)" },
  { term: "Activist investors", body: "Funds demanding higher dividends, buybacks, or management improvements from companies" },
  { term: "Wealthy individuals / \"whales\"", body: "Individual investors who nonetheless move hundreds of millions of yen" },
];

const WHY_ITEMS = [
  { term: "Reading the flow of capital (trends)", body: "Sustained stock-price rises and falls are driven by big investors accumulating or selling. This matters as a trend-following signal." },
  { term: "Screening for stock selection", body: "Whether a company's fundamentals and growth meet the research bar of large professional investors serves as a useful filter." },
];

const DATA_ITEMS = [
  "Deal information is fetched daily from EDINET large-shareholding reports. Both directions are covered — increases (acquisitions) and decreases (transfers/sales) in holding ratio — with sell-direction articles tagged \"Sell\".",
  "Deal size is an estimate calculated from shares outstanding × share price × change in holding ratio. EDINET disclosures themselves do not state a yen amount, so this is not a guaranteed exact figure.",
  "Articles are generated by AI from the filing's factual data, and reviewed or corrected by a human as needed. The English edition is a translation of the Japanese article; only a subset of articles has an English edition.",
  "Where a source (timely disclosure, press release, etc.) is identifiable, a link is included in the article.",
];

export default function EnAboutPage() {
  return (
    <article className="border-t border-rule bg-paper p-6 sm:p-10">
      <h1 className="mb-6 text-2xl font-bold text-brand-navy sm:text-3xl">{title}</h1>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">Who are &quot;big investors&quot;?</h2>
        <p className="text-sm leading-relaxed text-ink-secondary">
          Investment entities that manage capital large enough to move market prices in stocks and other
          financial markets.
        </p>
        <ul className="mt-3 list-disc space-y-1 pl-5 text-sm leading-relaxed text-ink-secondary">
          {WHO_ITEMS.map((item) => (
            <li key={item.term}>
              <strong className="text-brand-navy">{item.term}</strong>: {item.body}
            </li>
          ))}
        </ul>
        <p className="mt-3 text-sm leading-relaxed text-ink-secondary">
          This site classifies filers into {DEAL_TYPES.length} categories. See the{" "}
          <Link href="#dealtype-glossary" className="text-brand-blue hover:underline">glossary</Link> below.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">Why track big-investor moves</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-ink-secondary">
          {WHY_ITEMS.map((item) => (
            <li key={item.term}>
              <strong className="text-brand-navy">{item.term}</strong>: {item.body}
            </li>
          ))}
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">What &quot;big-investor moves&quot; means</h2>
        <p className="text-sm leading-relaxed text-ink-secondary">
          &quot;Big-investor moves&quot; refers to when and how much of a listed company&apos;s shares were bought
          or sold by an entity with market-moving capital — institutional investors, activist funds,
          founder-family holding companies, or the issuer itself through buybacks. In Japan, investors who
          acquire 5% or more of a company&apos;s shares must file a large-shareholding report with EDINET
          (the Financial Services Agency&apos;s disclosure system) — the so-called &quot;5% rule&quot; — and must
          re-file a change report if their holding ratio moves by 1 percentage point or more. This site
          tracks that public information daily.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">About this site</h2>
        <p className="text-sm leading-relaxed text-ink-secondary">
          {SITE_NAME_EN} is the English edition of{" "}
          <a href={SITE_URL} hrefLang="ja" className="text-brand-blue hover:underline">
            大口投資家の監視ブログ (kujira-watch.com)
          </a>
          , a blog that monitors and explains the moves of &quot;whales&quot; (financial-industry slang for
          large investors with enough capital to move the market) based on public information such as
          EDINET large-shareholding reports. The Japanese edition carries every disclosure along with
          per-stock and per-investor holding histories; the English edition covers a subset of articles.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">Data sources &amp; update method</h2>
        <ul className="list-disc space-y-1 pl-5 text-sm leading-relaxed text-ink-secondary">
          {DATA_ITEMS.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">About the source (EDINET)</h2>
        <p className="text-sm leading-relaxed text-ink-secondary">
          The disclosure information this site covers comes from EDINET, the official electronic
          disclosure system operated by Japan&apos;s Financial Services Agency (FSA). You can search the
          original filings yourself using the links below.
        </p>
        <ul className="mt-3 list-disc space-y-1 pl-5 text-sm leading-relaxed text-ink-secondary">
          <li>
            <a href="https://disclosure2.edinet-fsa.go.jp/" target="_blank" rel="noopener noreferrer" className="text-brand-blue hover:underline">
              EDINET (document search)
            </a>
          </li>
          <li>
            <a
              href="https://disclosure2dl.edinet-fsa.go.jp/guide/static/disclosure/WZEK0110.html"
              target="_blank"
              rel="noopener noreferrer"
              className="text-brand-blue hover:underline"
            >
              EDINET API specification
            </a>{" "}
            (the official FSA API this site uses for automated retrieval)
          </li>
        </ul>
      </section>

      <section id="dealtype-glossary" className="mb-6 scroll-mt-20">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">Investor classification (glossary)</h2>
        <p className="mb-3 text-sm leading-relaxed text-ink-secondary">
          The label on each article classifies the filer of the large-shareholding report into one of the
          categories below.
        </p>
        <dl className="m-0 flex flex-col gap-3">
          {DEAL_TYPES.map((dealType) => (
            <div key={dealType}>
              <dt className="font-semibold text-brand-navy">{DEAL_TYPE_EN[dealType].label}</dt>
              <dd className="m-0 text-sm text-ink-secondary">{DEAL_TYPE_EN[dealType].description}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-xl font-bold text-brand-navy">Contact</h2>
        <p className="text-sm leading-relaxed text-ink-secondary">
          The operator does not publish a name or email address. Questions and corrections can be sent to{" "}
          <a href={X_PROFILE_URL} target="_blank" rel="noopener noreferrer" className="text-brand-blue hover:underline">
            @kujira_watch on X
          </a>
          .
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-xl font-bold text-brand-navy">Disclaimer</h2>
        <p className="text-sm leading-relaxed text-ink-secondary">
          The content of this site is for informational purposes only and does not recommend or solicit
          any specific security or investment decision. We do not guarantee the accuracy or completeness
          of the information provided, and the operator assumes no responsibility for any damages
          resulting from its use. Please make all investment decisions at your own risk.
        </p>
      </section>
    </article>
  );
}
